FROM ubuntu

MAINTAINER tecwang

RUN apt-get update    

RUN apt-get install -y git
RUN apt-get install -y vim
RUN apt-get install -y python-pip 
RUN apt-get install -y python2.7-dev  

RUN apt-get install -y openssl  
RUN apt-get install -y libssl-dev  
RUN apt-get install -y libffi-dev  