FROM ubuntu

MAINTAINER ubuntu-tec

RUN apt-get update    

# 没让你装python啊...为啥最后还装了两个版本的python
RUN apt-get install -y git
RUN apt-get install -y vim

RUN apt-get install -y nodejs
RUN apt-get install -y npm
RUN apt-get install -y gcc-snapshot